### ISSUE TITLE
Users can create, read, update, and delete a profile in the database

### ISSUE THREAD

**Issue by meganann201** [meganann201/group-project-two#1]
- As a user, I can create my own profile that stores info about me (username, email, and password).
- As a user, I can retrieve my profile data or another user's profile data.
- As a user, I can update my profile data.
- As a user, I can delete my profile.

**Comment by vieiragcv** [comment]
User data:
-first_name
-last_name
-email
-user_name
-password

**Comment by meganann201** [comment]
We need routes for users. routes to create new account, login, logout, delete user, find user by id (include recipe and comment model).

**Comment by vieiragcv** [comment]
logged in/out can be a boolean for access. No need to include the concept of account or a model/route for it. Agree?
